spring:
   datasource:
      url: jdbc:mysql://localhost:3306/YOUR_DB_NAME?useTimezone=true&serverTimezone=UTC&useLegacyDate
      username: YOUR_DB_USERNAME
      password: YOUR_DB_PASSWORD
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         '[hibernate.format_sql]': true
   profiles:
      active: dev